export const GET_LIST_OF_TASKS = 'GET_LIST_OF_TASKS';
export const SAVE_LIST_OF_TASKS = 'SAVE_LIST_OF_TASKS';
export const GET_TODAY_SPENT_TIME = 'GET_TODAY_SPENT_TIME';
export const SAVE_TODAY_SPENT_TIME = 'SAVE_TODAY_SPENT_TIME';